title: Drew Seewald # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist at DTE Energy
  <br><br>
  <a href="https://www.linkedin.com/in/realdrewdata/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
